name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        if: ${{ github.event_name == 'push' && github.event.head_commit.message != 'skip ci' }}
        run: |
          # Run Cypress tests in the Functional-tests directory
          npx cypress run --spec "cypress/e2e/Functional-tests/**/*"

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-artifacts
          path: cypress/reports/html
          retention-days: 1
