name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conditional Cypress run
        if: ${{ github.event_name == 'push' && github.event.head_commit.message != 'skip ci' }}
        run: |
          # Install npm dependencies
          npm install

          # Run Cypress tests, excluding specific feature file
          npx cypress run --config excludeFiles='**/Cucumber-tests/ecommerce.feature'

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: cypress/reports/html, cypress/cucumberReports/html
          retention-days: 1
